// This is an autogenerated file from Firebase Studio.

/**
 * @fileOverview This file defines a Genkit flow for automatically categorizing products using GenAI.
 *
 * It exports:
 * - `categorizeProduct`: An async function that takes a product name and returns its category.
 * - `CategorizeProductInput`: The input type for the `categorizeProduct` function.
 * - `CategorizeProductOutput`: The output type for the `categorizeProduct` function.
 */

import {generateText} from '@/lib/gemini';
import {z} from 'genkit';

const CategoriesEnum = z.enum([
  "Frutas y Verduras",
  "Lácteos y Huevos",
  "Proteínas",
  "Panadería y Cereales",
  "Aperitivos",
  "Bebidas",
  "Hogar y Limpieza",
  "Condimentos y Especias",
  "Conservas y Despensa",
  "Otros"
]);

const CategorizeProductInputSchema = z.object({
  productName: z.string().describe('The name of the product to categorize.'),
});
export type CategorizeProductInput = z.infer<typeof CategorizeProductInputSchema>;

const CategorizeProductOutputSchema = z.object({
  category: CategoriesEnum.describe('The category of the product.'),
});
export type CategorizeProductOutput = z.infer<typeof CategorizeProductOutputSchema>;

export async function categorizeProduct(input: CategorizeProductInput): Promise<CategorizeProductOutput> {
  const prompt = `Eres un asistente de categorización de productos para una aplicación de gestión de despensa. Tu única función es asignar una categoría a un producto de una lista estrictamente definida, pensando en cómo se usa y almacena en un hogar.

**LISTA DE CATEGORÍAS VÁLIDAS:**
- "Frutas y Verduras"
- "Lácteos y Huevos"
- "Proteínas"
- "Panadería y Cereales"
- "Aperitivos"
- "Bebidas"
- "Hogar y Limpieza"
- "Condimentos y Especias"
- "Conservas y Despensa"
- "Otros"

**INSTRUCCIONES CLAVE:**
1.  **Contexto es todo:** Piensa en el uso final del producto en una despensa. Por ejemplo, la "manzanilla" es una hierba, pero se usa para hacer una infusión, por lo que su categoría es "Bebidas". El "atún en lata" es pescado, pero se almacena como una conserva, así que va en "Conservas y Despensa".
2.  Analiza el nombre del producto: "${input.productName}"
3.  Elige la categoría MÁS apropiada de la lista.
4.  **Formato estricto:** Tu respuesta DEBE ser un objeto JSON que contenga solo una clave, "category", con el valor exacto de la categoría.

**PRODUCTO A CLASIFICAR:**
${input.productName}`;

  const text = await generateText(prompt);
  try {
    const parsed = JSON.parse(text);
    if (parsed?.category) {
      return { category: parsed.category } as CategorizeProductOutput;
    }
  } catch {
    // ignore parsing errors
  }
  return { category: 'Otros' } as CategorizeProductOutput;
}
